package com.ninsky.cronos.domain.model.audit;

import static com.ninsky.cronos.domain.model.audit.AuditCategory.ACCESS_CONTROL;
import static com.ninsky.cronos.domain.model.audit.AuditCategory.AUTHENTICATION;
import static com.ninsky.cronos.domain.model.audit.AuditCategory.CONFIGURATION;
import static com.ninsky.cronos.domain.model.audit.AuditCategory.DATA;
import static com.ninsky.cronos.domain.model.audit.AuditCategory.SECURITY;
import static com.ninsky.cronos.domain.model.audit.AuditCategory.USER_ADMINISTRATION;

/** Every action the ledger records, each with its category (spec §7.2). */
public enum AuditAction {
    // Legacy admin endpoints (kept for one release)
    USER_CREATED_WITH_PROFILE(USER_ADMINISTRATION),
    USER_ROLES_ASSIGNED(ACCESS_CONTROL),
    USER_FORCE_LOGOUT(SECURITY),
    USER_TWO_FACTOR_DISABLED(SECURITY),
    USER_PASSWORD_RESET_INITIATED(SECURITY),
    // Account settings (self-service, actor == target)
    PROFILE_CHANGED(USER_ADMINISTRATION),
    AVATAR_CHANGED(USER_ADMINISTRATION),
    AVATAR_REMOVED(USER_ADMINISTRATION),
    FISCAL_DATA_CREATED(USER_ADMINISTRATION),
    FISCAL_DATA_UPDATED(USER_ADMINISTRATION),
    // Unit catalog (system-wide master data; every change restates conversions for all users)
    UNIT_TYPE_CREATED(CONFIGURATION),
    UNIT_TYPE_UPDATED(CONFIGURATION),
    UNIT_TYPE_STATUS_CHANGED(CONFIGURATION),
    UNIT_TYPE_DELETED(CONFIGURATION),
    MEASUREMENT_UNIT_CREATED(CONFIGURATION),
    MEASUREMENT_UNIT_UPDATED(CONFIGURATION),
    MEASUREMENT_UNIT_STATUS_CHANGED(CONFIGURATION),
    MEASUREMENT_UNIT_DELETED(CONFIGURATION),
    // Bulk imports: one entry per batch outcome; row-level detail lives in data_import_batches
    DATA_IMPORT_COMMITTED(DATA),
    DATA_IMPORT_REJECTED(DATA),
    DATA_IMPORT_FAILED(DATA),

    // Authentication
    LOGIN_SUCCEEDED(AUTHENTICATION),
    LOGIN_FAILED(AUTHENTICATION),
    LOGOUT(AUTHENTICATION),
    TOKEN_REFRESHED(AUTHENTICATION),
    TWO_FACTOR_FAILED(AUTHENTICATION),
    PASSWORD_CHANGED(AUTHENTICATION),
    PASSWORD_RESET_COMPLETED(AUTHENTICATION),
    INVITATION_ACCEPTED(AUTHENTICATION),

    // User administration
    USER_CREATED(USER_ADMINISTRATION),
    USER_UPDATED(USER_ADMINISTRATION),
    USER_RENAMED(USER_ADMINISTRATION),
    USER_EMAIL_CHANGED(USER_ADMINISTRATION),
    USER_STATUS_CHANGED(USER_ADMINISTRATION),
    USER_AVATAR_CHANGED(USER_ADMINISTRATION),
    USER_EXPORT(USER_ADMINISTRATION),
    USER_BULK_OPERATION(USER_ADMINISTRATION),
    INVITATION_RESENT(USER_ADMINISTRATION),
    INVITATION_DELIVERY_FAILED(USER_ADMINISTRATION),
    USER_PASSWORD_CHANGE_REQUIRED(USER_ADMINISTRATION),

    // Access control
    USER_ACCESS_CHANGED(ACCESS_CONTROL),
    ROLE_CREATED(ACCESS_CONTROL),
    ROLE_UPDATED(ACCESS_CONTROL),
    ROLE_STATUS_CHANGED(ACCESS_CONTROL),
    ROLE_DELETED(ACCESS_CONTROL),
    ROLE_CLONED(ACCESS_CONTROL),
    PERMISSION_GROUP_CREATED(ACCESS_CONTROL),
    PERMISSION_GROUP_UPDATED(ACCESS_CONTROL),
    PERMISSION_GROUP_STATUS_CHANGED(ACCESS_CONTROL),
    PERMISSION_GROUP_DELETED(ACCESS_CONTROL),
    ACCESS_DENIED(ACCESS_CONTROL),
    PRIVILEGE_ESCALATION_BLOCKED(ACCESS_CONTROL),
    SOD_CONFLICT_ACCEPTED(ACCESS_CONTROL),

    // Security
    USER_LOCKED(SECURITY),
    USER_UNLOCKED(SECURITY),
    USER_PASSWORD_RESET_ISSUED(SECURITY),
    USER_2FA_RESET(SECURITY),
    USER_SESSION_REVOKED(SECURITY),
    USER_SESSIONS_REVOKED(SECURITY),
    SECURITY_POLICY_UPDATED(SECURITY),
    AUDIT_CHAIN_VERIFIED(SECURITY),

    // Configuration (finance)
    CURRENCY_CREATED(CONFIGURATION),
    CURRENCY_UPDATED(CONFIGURATION),
    CURRENCY_STATUS_CHANGED(CONFIGURATION),
    CURRENCY_DELETED(CONFIGURATION),
    TAX_RATE_CREATED(CONFIGURATION),
    TAX_RATE_UPDATED(CONFIGURATION),
    TAX_RATE_STATUS_CHANGED(CONFIGURATION),
    TAX_RATE_DELETED(CONFIGURATION),
    FINANCE_DEFAULT_CHANGED(CONFIGURATION),
    FINANCE_DEFAULT_EXPIRED(CONFIGURATION),
    FINANCE_SETTINGS_UPDATED(CONFIGURATION),

    // Data
    AUDIT_EXPORT(DATA);

    private final AuditCategory category;

    AuditAction(AuditCategory category) {
        this.category = category;
    }

    public AuditCategory category() {
        return category;
    }
}
