-- Kitchen catalog & recipe studio (kitchen-catalog-and-recipes.md §9).
-- Legacy tables whose names the new model reuses are renamed to legacy_* and kept read-only for
-- one release; recipes is evolved in place so shares and quotes keep their references.

CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Accent/case folding usable in indexes (unaccent itself is only STABLE).
CREATE OR REPLACE FUNCTION kitchen_fold(value TEXT) RETURNS TEXT
    LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $$ SELECT lower(public.unaccent('public.unaccent'::regdictionary, value)) $$;

-- Stable code from free text: FOO_BAR, starts with a letter, 2..max chars.
CREATE OR REPLACE FUNCTION kitchen_code(value TEXT, fallback TEXT, max_length INT) RETURNS TEXT
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$
SELECT CASE
           WHEN c IS NULL OR c = '' THEN fallback
           WHEN c !~ '^[A-Z]' THEN left(fallback || '_' || c, max_length)
           WHEN length(c) < 2 THEN c || '_X'
           ELSE left(c, max_length)
       END
FROM (SELECT btrim(upper(regexp_replace(kitchen_fold(coalesce(value, '')), '[^a-z0-9]+', '_', 'g')), '_') AS c) s
$$;

-- ─── legacy renames ─────────────────────────────────────────────────────────────────────
DO $$
DECLARE
    t TEXT;
    idx RECORD;
BEGIN
    FOREACH t IN ARRAY ARRAY['allergens', 'ingredient_substitutes', 'recipe_fixed_costs', 'recipe_files'] LOOP
        IF to_regclass('public.' || t) IS NOT NULL THEN
            FOR idx IN SELECT indexname FROM pg_indexes WHERE schemaname = 'public' AND tablename = t LOOP
                EXECUTE format('ALTER INDEX %I RENAME TO %I', idx.indexname, left('legacy_' || idx.indexname, 63));
            END LOOP;
            EXECUTE format('ALTER TABLE %I RENAME TO %I', t, 'legacy_' || t);
        END IF;
    END LOOP;
END $$;

-- ─── categories: stable codes for SYSTEM rows ───────────────────────────────────────────
ALTER TABLE categories ADD COLUMN code VARCHAR(50);
CREATE UNIQUE INDEX ux_categories_system_code ON categories (type, code) WHERE scope = 'SYSTEM' AND code IS NOT NULL;

-- ─── allergens ──────────────────────────────────────────────────────────────────────────
CREATE TABLE allergens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)   NOT NULL,
    owner_id    UUID REFERENCES users (id),
    owner_key   UUID GENERATED ALWAYS AS (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
    icon        VARCHAR(40)   NOT NULL,
    regulations VARCHAR(20)[] NOT NULL DEFAULT '{}',
    status      VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    legacy_id   UUID          NOT NULL DEFAULT gen_random_uuid(),
    version     BIGINT        NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    CONSTRAINT ck_allergens_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_allergens_code CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$')
);
CREATE UNIQUE INDEX ux_allergens_code ON allergens (owner_key, code);
CREATE UNIQUE INDEX ux_allergens_legacy_id ON allergens (legacy_id);
CREATE INDEX ix_allergens_owner ON allergens (owner_id);

CREATE TABLE allergen_i18n (
    allergen_id BIGINT       NOT NULL REFERENCES allergens (id) ON DELETE CASCADE,
    locale      VARCHAR(5)   NOT NULL,
    name        VARCHAR(80)  NOT NULL,
    description VARCHAR(500),
    PRIMARY KEY (allergen_id, locale)
);

CREATE TABLE allergen_keywords (
    allergen_id BIGINT      NOT NULL REFERENCES allergens (id) ON DELETE CASCADE,
    owner_id    UUID REFERENCES users (id),
    owner_key   UUID GENERATED ALWAYS AS (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
    locale      VARCHAR(5)  NOT NULL,
    keyword     VARCHAR(40) NOT NULL,
    PRIMARY KEY (allergen_id, owner_key, locale, keyword)
);
CREATE INDEX ix_allergen_keywords_owner ON allergen_keywords (owner_key);

-- ─── ingredients ────────────────────────────────────────────────────────────────────────
CREATE TABLE ingredients (
    id               UUID PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL,
    owner_id         UUID REFERENCES users (id),
    owner_key        UUID GENERATED ALWAYS AS (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
    category_id      BIGINT       NOT NULL REFERENCES categories (id),
    base_dimension   VARCHAR(6)   NOT NULL,
    yield_percent    NUMERIC(5, 1) NOT NULL,
    density_g_per_ml NUMERIC(6, 3),
    brand            VARCHAR(80),
    status           VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID,
    updated_at       TIMESTAMPTZ,
    updated_by       UUID,
    CONSTRAINT ck_ingredients_code CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    CONSTRAINT ck_ingredients_dimension CHECK (base_dimension IN ('MASS', 'VOLUME', 'COUNT')),
    CONSTRAINT ck_ingredients_yield CHECK (yield_percent BETWEEN 1 AND 100),
    CONSTRAINT ck_ingredients_density CHECK (density_g_per_ml BETWEEN 0.1 AND 3),
    CONSTRAINT ck_ingredients_count_density CHECK (base_dimension <> 'COUNT' OR density_g_per_ml IS NULL),
    CONSTRAINT ck_ingredients_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE UNIQUE INDEX ux_ingredients_code ON ingredients (owner_key, code);
CREATE INDEX ix_ingredients_owner ON ingredients (owner_id);
CREATE INDEX ix_ingredients_category ON ingredients (category_id);

CREATE TABLE ingredient_i18n (
    ingredient_id UUID         NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
    locale        VARCHAR(5)   NOT NULL,
    name          VARCHAR(120) NOT NULL,
    description   VARCHAR(500),
    PRIMARY KEY (ingredient_id, locale)
);
CREATE INDEX ix_ingredient_i18n_name ON ingredient_i18n USING gin (kitchen_fold(name) gin_trgm_ops);

CREATE TABLE ingredient_allergens (
    ingredient_id UUID   NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
    allergen_id   BIGINT NOT NULL REFERENCES allergens (id),
    PRIMARY KEY (ingredient_id, allergen_id)
);
CREATE INDEX ix_ingredient_allergens_allergen ON ingredient_allergens (allergen_id);

-- PK includes the owner: two tenants may declare the same pair on a SYSTEM ingredient.
CREATE TABLE ingredient_substitutes (
    ingredient_id UUID          NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
    substitute_id UUID          NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
    owner_id      UUID REFERENCES users (id),
    owner_key     UUID GENERATED ALWAYS AS (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
    ratio         NUMERIC(7, 3) NOT NULL,
    notes         VARCHAR(200),
    PRIMARY KEY (ingredient_id, substitute_id, owner_key),
    CONSTRAINT ck_ingredient_substitutes_ratio CHECK (ratio BETWEEN 0.01 AND 10),
    CONSTRAINT ck_ingredient_substitutes_self CHECK (ingredient_id <> substitute_id)
);
CREATE INDEX ix_ingredient_substitutes_substitute ON ingredient_substitutes (substitute_id);

-- Append-only price history; owner_id NULL = platform reference price.
CREATE TABLE ingredient_prices (
    id                 UUID PRIMARY KEY,
    ingredient_id      UUID           NOT NULL REFERENCES ingredients (id) ON DELETE CASCADE,
    owner_id           UUID REFERENCES users (id),
    purchase_quantity  NUMERIC(14, 4) NOT NULL,
    purchase_unit_id   BIGINT         NOT NULL REFERENCES measurement_units (id),
    price              NUMERIC(14, 4) NOT NULL,
    currency           CHAR(3)        NOT NULL,
    supplier           VARCHAR(120),
    priced_at          DATE           NOT NULL,
    cost_per_base_unit NUMERIC(18, 8) NOT NULL,
    recorded_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    recorded_by        UUID,
    CONSTRAINT ck_ingredient_prices_quantity CHECK (purchase_quantity > 0),
    CONSTRAINT ck_ingredient_prices_price CHECK (price > 0)
);
CREATE INDEX ix_ingredient_prices_latest ON ingredient_prices (ingredient_id, owner_id, priced_at DESC, recorded_at DESC);
CREATE INDEX ix_ingredient_prices_unit ON ingredient_prices (purchase_unit_id);

CREATE OR REPLACE FUNCTION prevent_ingredient_price_modification() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'ingredient_prices is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ingredient_prices_append_only
    BEFORE UPDATE ON ingredient_prices
    FOR EACH ROW EXECUTE FUNCTION prevent_ingredient_price_modification();

-- ─── recipes (evolved in place) ─────────────────────────────────────────────────────────
ALTER TABLE recipes RENAME COLUMN user_id TO owner_id;
ALTER TABLE recipes ALTER COLUMN owner_id DROP NOT NULL;
ALTER TABLE recipes RENAME COLUMN category_id TO legacy_category_id;
ALTER TABLE recipes RENAME COLUMN preparation_time_minutes TO prep_minutes;
ALTER TABLE recipes RENAME COLUMN baking_time_minutes TO bake_minutes;
ALTER TABLE recipes RENAME COLUMN cooling_time_minutes TO cool_minutes;

ALTER TABLE recipes
    ADD COLUMN code                  VARCHAR(50),
    ADD COLUMN category_id           BIGINT REFERENCES categories (id),
    ADD COLUMN difficulty            VARCHAR(8)    NOT NULL DEFAULT 'EASY',
    ADD COLUMN process_html          TEXT,
    ADD COLUMN oven_temperature_c    INT,
    ADD COLUMN target_margin_percent NUMERIC(7, 2) NOT NULL DEFAULT 60,
    ADD COLUMN waste_percent         NUMERIC(5, 2) NOT NULL DEFAULT 3,
    ADD COLUMN ingredients_cost      NUMERIC(14, 4),
    ADD COLUMN waste_cost            NUMERIC(14, 4),
    ADD COLUMN fixed_costs           NUMERIC(14, 4),
    ADD COLUMN cost_per_unit         NUMERIC(14, 4),
    ADD COLUMN suggested_unit_price  NUMERIC(14, 4),
    ADD COLUMN unpriced_lines        INT           NOT NULL DEFAULT 0,
    ADD COLUMN cost_status           VARCHAR(10)   NOT NULL DEFAULT 'INCOMPLETE',
    ADD COLUMN cost_calculated_at    TIMESTAMPTZ,
    ADD COLUMN deleted_at            TIMESTAMPTZ,
    ADD COLUMN created_by_id         UUID,
    ADD COLUMN updated_by_id         UUID;

ALTER TABLE recipes ALTER COLUMN total_cost TYPE NUMERIC(14, 4);
ALTER TABLE recipes ALTER COLUMN total_cost DROP DEFAULT;
ALTER TABLE recipes ALTER COLUMN yield_quantity TYPE NUMERIC(12, 2);
ALTER TABLE recipes ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'America/Mexico_City';
ALTER TABLE recipes ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE recipes ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'America/Mexico_City';
UPDATE recipes SET version = 0 WHERE version IS NULL;
ALTER TABLE recipes ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE recipes ALTER COLUMN version SET NOT NULL;

UPDATE recipes SET status = CASE
    WHEN NOT is_active THEN 'ARCHIVED'
    WHEN upper(status) IN ('ACTIVE', 'PUBLISHED') THEN 'ACTIVE'
    WHEN upper(status) = 'ARCHIVED' THEN 'ARCHIVED'
    ELSE 'DRAFT' END;
UPDATE recipes SET cost_status = 'STALE' WHERE needs_recalculation;
ALTER TABLE recipes ALTER COLUMN status TYPE VARCHAR(10);
ALTER TABLE recipes ALTER COLUMN status SET DEFAULT 'DRAFT';
ALTER TABLE recipes DROP COLUMN is_active, DROP COLUMN needs_recalculation, DROP COLUMN current_version;

-- Plain-text instructions become an escaped paragraph of process HTML.
UPDATE recipes
SET process_html = '<p>' || replace(replace(replace(replace(btrim(instructions), '&', '&amp;'), '<', '&lt;'), '>', '&gt;'), E'\n', '<br>') || '</p>'
WHERE instructions IS NOT NULL AND btrim(instructions) <> '';

-- Unique names per owner among live rows: later duplicates get " (n)".
WITH ranked AS (
    SELECT id, row_number() OVER (PARTITION BY owner_id, kitchen_fold(name) ORDER BY created_at, id) AS n FROM recipes)
UPDATE recipes r SET name = left(r.name, 110) || ' (' || ranked.n || ')'
FROM ranked WHERE ranked.id = r.id AND ranked.n > 1;

WITH ranked AS (
    SELECT id, kitchen_code(name, 'RECIPE', 50) AS base,
           row_number() OVER (PARTITION BY owner_id, kitchen_code(name, 'RECIPE', 50) ORDER BY created_at, id) AS n
    FROM recipes)
UPDATE recipes r SET code = CASE WHEN ranked.n = 1 THEN ranked.base ELSE left(ranked.base, 44) || '_' || ranked.n END
FROM ranked WHERE ranked.id = r.id;

ALTER TABLE recipes ALTER COLUMN code SET NOT NULL;
ALTER TABLE recipes
    ADD CONSTRAINT ck_recipes_code CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    ADD CONSTRAINT ck_recipes_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    ADD CONSTRAINT ck_recipes_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'ADVANCED')),
    ADD CONSTRAINT ck_recipes_cost_status CHECK (cost_status IN ('CURRENT', 'STALE', 'INCOMPLETE')),
    ADD CONSTRAINT ck_recipes_yield CHECK (yield_quantity > 0);

CREATE UNIQUE INDEX ux_recipes_code ON recipes (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid), code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_recipes_name ON recipes (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid), kitchen_fold(name)) WHERE deleted_at IS NULL;
CREATE INDEX ix_recipes_owner_updated ON recipes (owner_id, updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE recipe_lines (
    id               UUID PRIMARY KEY,
    recipe_id        UUID           NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    ingredient_id    UUID           NOT NULL REFERENCES ingredients (id),
    section          VARCHAR(40),
    quantity         NUMERIC(14, 4) NOT NULL,
    unit_id          BIGINT         NOT NULL REFERENCES measurement_units (id),
    optional         BOOLEAN        NOT NULL DEFAULT FALSE,
    quote_selectable BOOLEAN        NOT NULL DEFAULT FALSE,
    notes            VARCHAR(200),
    display_order    INT            NOT NULL,
    line_cost        NUMERIC(14, 4),
    CONSTRAINT ck_recipe_lines_quantity CHECK (quantity > 0),
    CONSTRAINT ck_recipe_lines_optional CHECK (NOT optional OR quote_selectable)
);
CREATE INDEX ix_recipe_lines_recipe ON recipe_lines (recipe_id, display_order);
CREATE INDEX ix_recipe_lines_ingredient ON recipe_lines (ingredient_id);
CREATE INDEX ix_recipe_lines_unit ON recipe_lines (unit_id);

CREATE TABLE recipe_line_allergens (
    line_id     UUID       NOT NULL REFERENCES recipe_lines (id) ON DELETE CASCADE,
    allergen_id BIGINT     NOT NULL REFERENCES allergens (id),
    source      VARCHAR(8) NOT NULL,
    PRIMARY KEY (line_id, allergen_id),
    CONSTRAINT ck_recipe_line_allergens_source CHECK (source IN ('DETECTED', 'MANUAL'))
);
CREATE INDEX ix_recipe_line_allergens_allergen ON recipe_line_allergens (allergen_id);

CREATE TABLE recipe_fixed_costs (
    id                 UUID PRIMARY KEY,
    recipe_id          UUID NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    user_fixed_cost_id UUID NOT NULL REFERENCES user_fixed_costs (id),
    minutes            INT,
    percentage         NUMERIC(5, 2),
    cost               NUMERIC(14, 4),
    UNIQUE (recipe_id, user_fixed_cost_id)
);
CREATE INDEX ix_recipe_fixed_costs_master ON recipe_fixed_costs (user_fixed_cost_id);

-- sha256 is nullable only for rows migrated from legacy_recipe_files (never hashed).
CREATE TABLE recipe_files (
    id            UUID PRIMARY KEY,
    recipe_id     UUID         NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    storage_key   VARCHAR(300) NOT NULL,
    file_name     VARCHAR(150) NOT NULL,
    kind          VARCHAR(12)  NOT NULL,
    mime_type     VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    sha256        CHAR(64),
    description   VARCHAR(200),
    is_cover      BOOLEAN      NOT NULL DEFAULT FALSE,
    thumbnail_key VARCHAR(300),
    uploaded_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    uploaded_by   UUID,
    CONSTRAINT ck_recipe_files_kind CHECK (kind IN ('IMAGE', 'PDF', 'DOCUMENT', 'SPREADSHEET', 'VIDEO'))
);
CREATE UNIQUE INDEX ux_recipe_files_cover ON recipe_files (recipe_id) WHERE is_cover;
CREATE INDEX ix_recipe_files_recipe ON recipe_files (recipe_id, uploaded_at);

CREATE TABLE recipe_revisions (
    recipe_id      UUID        NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
    version        BIGINT      NOT NULL,
    changed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by     UUID,
    summary_key    VARCHAR(80) NOT NULL,
    summary_params JSONB       NOT NULL DEFAULT '{}',
    changes        JSONB       NOT NULL DEFAULT '{}',
    cost_per_unit  NUMERIC(14, 4),
    PRIMARY KEY (recipe_id, version)
);

-- ─── quotes ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE quote_items
    ADD COLUMN recipe_configuration  JSONB,
    ADD COLUMN allergens             JSONB       NOT NULL DEFAULT '[]',
    ADD COLUMN recipe_version        BIGINT,
    ADD COLUMN cost_calculated_at    TIMESTAMPTZ,
    ADD COLUMN price_review_required BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE quotes ADD COLUMN price_review_required BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS ix_quote_items_recipe ON quote_items (recipe_id) WHERE recipe_id IS NOT NULL;

-- ─── background work (reference-price ripple, oversized ripples) ────────────────────────
CREATE TABLE kitchen_jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         VARCHAR(30)  NOT NULL,
    payload      JSONB        NOT NULL,
    status       VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    attempts     INT          NOT NULL DEFAULT 0,
    last_error   VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    CONSTRAINT ck_kitchen_jobs_kind CHECK (kind IN ('RECALCULATE_RECIPES')),
    CONSTRAINT ck_kitchen_jobs_status CHECK (status IN ('PENDING', 'DONE', 'FAILED'))
);
CREATE INDEX ix_kitchen_jobs_pending ON kitchen_jobs (id) WHERE status = 'PENDING';
