    create table public.device_fingerprints (
        is_trusted boolean not null,
        login_count integer DEFAULT 0 not null,
        first_seen_at timestamp(6) not null,
        last_seen_at timestamp(6),
        trusted_at timestamp(6),
        id uuid not null,
        user_id uuid not null,
        ip_address varchar(45),
        device_type varchar(50),
        browser varchar(100),
        location varchar(100),
        operating_system varchar(100),
        device_name varchar(200),
        user_agent varchar(500),
        fingerprint_hash varchar(255) not null,
        primary key (id),
        constraint uq_user_fingerprint unique (user_id, fingerprint_hash)
    );

    create table public.password_history (
        changed_at timestamp(6) not null,
        id uuid not null,
        user_id uuid not null,
        password_hash varchar(500) not null,
        primary key (id)
    );

    create table public.password_reset_tokens (
        used boolean not null,
        created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP not null,
        expires_at timestamp(6) not null,
        id uuid not null,
        user_id uuid not null,
        token varchar(500) not null unique,
        primary key (id)
    );

    create table public.security_notifications (
        email_sent boolean not null,
        is_read boolean not null,
        created_at timestamp(6) not null,
        email_sent_at timestamp(6),
        read_at timestamp(6),
        id uuid not null,
        user_id uuid not null,
        severity varchar(20) not null,
        ip_address varchar(45),
        type varchar(50) not null,
        browser varchar(100),
        location varchar(100),
        operating_system varchar(100),
        device_name varchar(200),
        title varchar(200) not null,
        message text,
        primary key (id)
    );

    create index idx_password_reset_token 
       on public.password_reset_tokens (token);

    create table allergens (
        is_system_default boolean,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','ARCHIVED')),
        created_by varchar(100),
        updated_by varchar(100),
        alternative_name varchar(255),
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table categories (
        is_system_default boolean,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        version bigint,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','ARCHIVED')),
        created_by varchar(100),
        updated_by varchar(100),
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table ingredient_conversions (
        factor numeric(20,10) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        mass_unit_id bigint not null,
        updated_at timestamp(6),
        user_id bigint,
        volume_unit_id bigint not null,
        ingredient_id uuid not null,
        created_by varchar(100),
        updated_by varchar(100),
        primary key (id)
    );

    create table ingredient_substitutes (
        conversion_ratio numeric(10,4) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        original_ingredient_id uuid not null,
        substitute_material_id uuid not null,
        user_id uuid not null,
        reason varchar(50),
        created_by varchar(100),
        updated_by varchar(100),
        notes TEXT,
        primary key (id)
    );

    create table login_history (
        successful boolean not null,
        two_factor_used boolean,
        created_at timestamp(6) not null,
        login_at timestamp(6) not null,
        status varchar(15),
        id uuid not null,
        user_id uuid not null,
        ip_address varchar(45),
        browser varchar(100),
        device varchar(100),
        location varchar(100),
        operating_system varchar(100),
        user_agent varchar(500),
        failure_reason varchar(255),
        primary key (id)
    );

    create table measurement_units (
        is_base_unit boolean not null,
        is_system_default boolean not null,
        multiplier_to_base numeric(20,10) not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        unit_type_id bigint not null,
        updated_at timestamp(6),
        user_id bigint,
        code_identity varchar(20) not null unique,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','ARCHIVED')),
        created_by varchar(100),
        name varchar(100) not null,
        name_plural varchar(100),
        updated_by varchar(100),
        primary key (id)
    );

    create table permissions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        action varchar(50),
        resource varchar(50),
        created_by varchar(100),
        name varchar(100) not null unique,
        updated_by varchar(100),
        description varchar(255),
        primary key (id)
    );

    create table quote_access_logs (
        accessed_at timestamp(6) not null,
        id uuid not null,
        quote_id uuid not null,
        ip_address varchar(45),
        user_agent varchar(500),
        primary key (id)
    );

    create table quote_items (
        display_order integer,
        profit_percentage numeric(5,2) not null,
        quantity numeric(15,4) not null,
        scale_factor numeric(10,4),
        subtotal numeric(15,2) not null,
        unit_cost numeric(15,6) not null,
        unit_price numeric(15,2) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        quote_id uuid not null,
        recipe_id uuid,
        created_by varchar(100),
        product_size varchar(100),
        updated_by varchar(100),
        image_file_path varchar(500),
        product_description varchar(1000),
        notes TEXT,
        product_name varchar(255) not null,
        primary key (id)
    );

    create table quotes (
        currency varchar(3) not null,
        delivery_fee numeric(15,2) not null,
        extra_fee numeric(15,2) not null,
        is_revoked boolean not null,
        subtotal numeric(15,2) not null,
        tax_amount numeric(15,2) not null,
        tax_rate numeric(5,2) not null,
        total numeric(15,2) not null,
        views_count integer not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        valid_until timestamp(6),
        version bigint,
        id uuid not null,
        user_id uuid not null,
        status varchar(20) not null check (status in ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CANCELED')),
        created_by varchar(100),
        public_token varchar(100) unique,
        quote_number varchar(100) not null unique,
        updated_by varchar(100),
        extra_fee_description varchar(200),
        notes varchar(2000),
        client_address TEXT,
        client_email TEXT,
        client_name TEXT not null,
        client_phone TEXT,
        primary key (id)
    );

    create table raw_material_allergens (
        allergen_id uuid not null,
        raw_material_id uuid not null,
        primary key (allergen_id, raw_material_id)
    );

    create table raw_materials (
        base_unit_cost numeric(15,6),
        currency varchar(3) not null,
        current_stock numeric(15,4),
        density numeric(10,4),
        minimum_stock numeric(15,4),
        needs_recalculation boolean not null,
        purchase_quantity numeric(15,4) not null,
        unit_cost numeric(15,2) not null,
        yield_percentage numeric(5,2) not null,
        category_id bigint not null,
        created_at timestamp(6) not null,
        last_price_update timestamp(6),
        last_purchase_date timestamp(6),
        purchase_unit_id bigint not null,
        updated_at timestamp(6),
        id uuid not null,
        user_id uuid,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','ARCHIVED')),
        created_by varchar(100),
        updated_by varchar(100),
        name varchar(200) not null,
        supplier varchar(500),
        brand varchar(255),
        description TEXT,
        primary key (id)
    );

    create table recipe_files (
        is_primary boolean,
        created_at timestamp(6) not null,
        file_size bigint,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        recipe_id uuid not null,
        file_type varchar(50) not null,
        storage_provider varchar(50),
        created_by varchar(100),
        mime_type varchar(100),
        updated_by varchar(100),
        description varchar(500),
        file_name varchar(500) not null,
        original_file_name varchar(500) not null,
        file_path varchar(1000) not null,
        public_url varchar(1000),
        thumbnail_path varchar(1000),
        primary key (id)
    );

    create table recipe_fixed_costs (
        calculated_amount numeric(15,4) not null,
        is_active boolean,
        percentage numeric(5,2),
        rate numeric(15,2) not null,
        time_in_minutes integer,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        master_fixed_cost_id uuid,
        recipe_id uuid not null,
        calculation_method varchar(50) not null,
        type varchar(50) not null,
        created_by varchar(100),
        updated_by varchar(100),
        description varchar(500),
        name varchar(255) not null,
        primary key (id)
    );

    create table recipe_ingredients (
        cost_per_unit numeric(15,6),
        display_order integer,
        is_optional boolean,
        quantity numeric(15,4) not null,
        total_cost numeric(15,2),
        created_at timestamp(6) not null,
        unit_id bigint not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        raw_material_id uuid not null,
        recipe_id uuid not null,
        created_by varchar(100),
        updated_by varchar(100),
        notes TEXT,
        primary key (id)
    );

    create table recipe_share_access_logs (
        accessed_at timestamp(6) not null,
        id uuid not null,
        recipe_share_id uuid not null,
        ip_address varchar(45),
        user_agent varchar(500),
        primary key (id)
    );

    create table recipe_shares (
        is_revoked boolean,
        views_count integer,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id uuid not null,
        recipe_id uuid not null,
        user_id uuid not null,
        share_token varchar(100) not null unique,
        recipient_email varchar(255),
        primary key (id)
    );

    create table recipe_sub_recipes (
        display_order integer,
        quantity numeric(15,4) not null,
        total_cost numeric(15,2),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        parent_recipe_id uuid not null,
        sub_recipe_id uuid not null,
        created_by varchar(100),
        updated_by varchar(100),
        notes TEXT,
        primary key (id)
    );

    create table recipes (
        baking_time_minutes integer,
        cooling_time_minutes integer,
        current_version integer not null,
        is_active boolean not null,
        needs_recalculation boolean not null,
        preparation_time_minutes integer,
        shelf_life_days integer,
        total_cost numeric(15,2),
        yield_quantity numeric(10,2) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        category_id uuid,
        id uuid not null,
        user_id uuid not null,
        status varchar(20) not null,
        yield_unit varchar(50) not null,
        created_by varchar(100),
        updated_by varchar(100),
        name varchar(200) not null,
        storage_instructions varchar(1000),
        description varchar(2000),
        instructions varchar(5000),
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        revoked_at timestamp(6),
        id uuid not null,
        session_id uuid,
        user_id uuid not null,
        token varchar(500) not null unique,
        ip_address varchar(255),
        user_agent varchar(255),
        primary key (id)
    );

    create table role_permissions (
        permission_id bigint not null,
        role_id bigint not null,
        primary key (permission_id, role_id)
    );

    create table roles (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(50) not null unique,
        created_by varchar(100),
        updated_by varchar(100),
        description varchar(255),
        primary key (id)
    );

    create table unit_types (
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        code_identity varchar(20) not null unique,
        status varchar(20) not null check (status in ('ACTIVE','INACTIVE','ARCHIVED')),
        dimension varchar(50) not null,
        created_by varchar(100),
        name varchar(100) not null,
        updated_by varchar(100),
        primary key (id)
    );

    create table user_fixed_costs (
        default_amount numeric(15,2) not null,
        is_active boolean,
        percentage numeric(5,2) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        version bigint,
        id uuid not null,
        user_id uuid not null,
        calculation_method varchar(50) not null,
        type varchar(50) not null,
        created_by varchar(100),
        updated_by varchar(100),
        description varchar(500),
        name varchar(255) not null,
        primary key (id)
    );

    create table user_profiles (
        default_tax_rate numeric(5,2),
        email_notifications boolean not null,
        push_notifications boolean not null,
        sms_notifications boolean not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        currency varchar(10),
        language varchar(10),
        id uuid not null,
        user_id uuid not null unique,
        timezone varchar(50),
        business_type varchar(100),
        created_by varchar(100),
        first_name varchar(100),
        last_name varchar(100),
        updated_by varchar(100),
        bio varchar(500),
        cover_picture_url varchar(500),
        profile_picture_url varchar(500),
        address TEXT,
        business_address TEXT,
        business_city TEXT,
        business_country TEXT,
        business_email TEXT,
        business_name TEXT,
        business_phone TEXT,
        business_postal_code TEXT,
        business_state TEXT,
        business_website varchar(255),
        city TEXT,
        country TEXT,
        date_of_birth TEXT,
        facebook_url varchar(255),
        gender TEXT,
        instagram_url varchar(255),
        linkedin_url varchar(255),
        phone_number TEXT,
        postal_code TEXT,
        state TEXT,
        tax_id TEXT,
        twitter_url varchar(255),
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id uuid not null,
        primary key (role_id, user_id)
    );

    create table user_sessions (
        is_active boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        last_activity_at timestamp(6),
        terminated_at timestamp(6),
        id uuid not null,
        user_id uuid not null,
        session_token varchar(500) not null unique,
        browser varchar(255),
        device varchar(255),
        device_id varchar(255),
        dpop_jkt varchar(255),
        ip_address varchar(255),
        location varchar(255),
        operating_system varchar(255),
        termination_reason varchar(255),
        user_agent varchar(255),
        primary key (id)
    );

    create table users (
        account_non_expired boolean not null,
        account_non_locked boolean not null,
        credentials_non_expired boolean not null,
        email_verified boolean not null,
        enabled boolean not null,
        failed_login_attempts integer not null,
        password_needs_change boolean not null,
        two_factor_enabled boolean not null,
        created_at timestamp(6) not null,
        last_failed_login timestamp(6),
        last_login_at timestamp(6),
        locked_until timestamp(6),
        password_changed_at timestamp(6),
        updated_at timestamp(6),
        id uuid not null,
        email_blind_index varchar(44) not null unique,
        created_by varchar(100),
        updated_by varchar(100),
        username varchar(100) not null unique,
        password varchar(500),
        email TEXT not null,
        two_factor_secret TEXT,
        primary key (id)
    );

    create index idx_user_ingredient_subs 
       on ingredient_substitutes (user_id, original_ingredient_id);

    create index idx_recipe_share_token 
       on recipe_shares (share_token);

    alter table if exists ingredient_conversions 
       add constraint FKjncimwcvgfb8b1sic5wcgk5p9 
       foreign key (mass_unit_id) 
       references measurement_units;

    alter table if exists ingredient_conversions 
       add constraint FKo33t0rqq702c9b1veh03ynccy 
       foreign key (volume_unit_id) 
       references measurement_units;

    alter table if exists measurement_units 
       add constraint FKcwvki7jgg11qdx5u7ub9rqc95 
       foreign key (unit_type_id) 
       references unit_types;

    alter table if exists quote_items 
       add constraint FKrvsmoef7yontnlu1lwxrb0g3g 
       foreign key (quote_id) 
       references quotes;

    alter table if exists raw_material_allergens 
       add constraint FKkjht5w9id4mrcsnmb0qa8yjst 
       foreign key (allergen_id) 
       references allergens;

    alter table if exists raw_material_allergens 
       add constraint FKje96tphaddiowng9v8t4qnxqh 
       foreign key (raw_material_id) 
       references raw_materials;

    alter table if exists raw_materials 
       add constraint FK2kr8urxw3up3k5x1lq1xdd2d3 
       foreign key (purchase_unit_id) 
       references measurement_units;

    alter table if exists recipe_fixed_costs 
       add constraint FKk0q97clamhbswx5m5j19h1wj2 
       foreign key (recipe_id) 
       references recipes;

    alter table if exists recipe_ingredients 
       add constraint FKcqlw8sor5ut10xsuj3jnttkc 
       foreign key (recipe_id) 
       references recipes;

    alter table if exists recipe_sub_recipes 
       add constraint FKqmt01onoekt3starkydhk0kbu 
       foreign key (parent_recipe_id) 
       references recipes;

    alter table if exists recipe_sub_recipes 
       add constraint FK1dwm6p5g29934jfowgc5w9d1f 
       foreign key (sub_recipe_id) 
       references recipes;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
